/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-05-02 07:01:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.menu;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class add_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("욘두가 좋아하는 메뉴 등록", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("center", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("메뉴 정보 입력", request.getCharacterEncoding()), out, false);
      out.write("\n");
      out.write("<style>\n");
      out.write("	#form div, label{\n");
      out.write("		margin:5px;\n");
      out.write("	}\n");
      out.write("</style>\n");
      out.write("<div class=\"row my-3\">\n");
      out.write("<div class=\"col-4\"></div>\n");
      out.write("<div class=\"col-4 border rounded p-2\">\n");
      out.write("<form action=\"/menu/add\" method=\"post\" id=\"form\">\n");
      out.write("	<label>\n");
      out.write("	<div>\n");
      out.write("		밥집명\n");
      out.write("		<input type=\"text\" readonly name=\"restaurantName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${newRstInfo.restaurantName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("	</div>\n");
      out.write("	</label>\n");
      out.write("	<label>\n");
      out.write("		메뉴명 : <input type=\"text\" name=\"menuName\" placeholder=\"후라이드/양념 반반\">\n");
      out.write("	</label>\n");
      out.write("	<label>\n");
      out.write("		가격 : <input type=\"text\" name=\"price\" class=\"price\">\n");
      out.write("	</label>\n");
      out.write("	<label>\n");
      out.write("		<select type=\"text\" name=\"category\">\n");
      out.write("			<option disabled>카테고리</option>\n");
      out.write("			<option value=\"밥\">밥</option>\n");
      out.write("			<option value=\"국/찌개\">국/찌개</option>\n");
      out.write("			<option value=\"면/분식\">면/분식</option>\n");
      out.write("			<option value=\"야식\">야식</option>\n");
      out.write("		</select>\n");
      out.write("	</label>\n");
      out.write("	<label>\n");
      out.write("		<input type=\"hidden\" name=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${newRstInfo.no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("	</label>\n");
      out.write("	<button id=\"btn\" class=\"btn btn-outline-dark\">완료</button>\n");
      out.write("	<button class=\"btn btn-outline-dark\" type=\"button\" onclick=\"/main\">취소</button>\n");
      out.write("</form>\n");
      out.write("<div class=\"col-4\"></div>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("<script>\n");
      out.write("	const btn = document.querySelector(\"#btn\");\n");
      out.write("	const menuEl = document.querySelector(\"[name='menuName']\");\n");
      out.write("	const priceEl = document.querySelector(\"[name='price']\");\n");
      out.write("	const categoryEl = document.querySelector(\"[name='category']\");\n");
      out.write("	\n");
      out.write("	btn.addEventListener(\"click\", function(e) {\n");
      out.write("		e.preventDefault();\n");
      out.write("		\n");
      out.write("		if(menuEl.value == \"\") {\n");
      out.write("			alert(\"메뉴명을 입력하세요.\");\n");
      out.write("			menuEl.focus();\n");
      out.write("			\n");
      out.write("		}else{\n");
      out.write("			if(priceEl.value == \"\") {\n");
      out.write("				alert(\"가격을 입력하세요\");\n");
      out.write("				priceEl.focus();\n");
      out.write("			}else{\n");
      out.write("				if(typeof parseInt(priceEl.value) != \"number\"){\n");
      out.write("					console.log(\"숫자만 입력 가능합니다.\");\n");
      out.write("					priceEl.value = \"\";\n");
      out.write("					priceEl.focus();\n");
      out.write("				}else{\n");
      out.write("					const form = document.querySelector(\"#form\");\n");
      out.write("					form.submit();\n");
      out.write("				}\n");
      out.write("			}\n");
      out.write("		}\n");
      out.write("	})\n");
      out.write("</script>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
